### PR TITLE
Feature thank you router

### LINKED ISSUE #56: Build out thank you routes

### PR DESCRIPTION
**Pull request by smmc16**
Added GET and POST routes  for thank you messages and updated database.sql. Resolves #56

### CODE REVIEW

**Review by lonsnw — COMMENTED** [review]
I don't think that there will be a recipient_id, and if there is, it wouldn't make sense for it to be in the "user" table, unless I'm imagining things differently.  The recipient and their info will all be in the "memento_box" table, so the request to pull the info we'll need for sending emails will come from that, I believe.  To send thank you emails, I think we'll need a store or similar that pulls the "recipient_email" and the "recipient_name" from "memento_box" (as well as a number of other things).

**Comment by smmc16** [comment]
The recipient id is for the collaborator thats receiving the thank you! My understanding is that collaborators should have an id.

**Comment by lonsnw** [comment]
That does make sense.  Can we call it something else?  Aren't we using recipient elsewhere to refer to the person who gets the box?  That seems like confusing phrasing.

**Comment by smmc16** [comment]
Sounds good I changed it to thanks_receiver_id.

**Comment by Iskander789** [comment]
Looks good.

**Review by Iskander789 — APPROVED** [review]

**Pull request merged**
